const DATA = {
  "players": [
    {
      "id": "jannik-sinner",
      "name": "Jannik Sinner",
      "country": "Italy",
      "flag": "🇮🇹",
      "rank": 1,
      "points": 15250,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 20,
      "bestRank": 1,
      "wins": 25,
      "losses": 2,
      "height": "178 cm",
      "bio": "Jannik Sinner enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "carlos-alcaraz",
      "name": "Carlos Alcaraz",
      "country": "Spain",
      "flag": "🇪🇸",
      "rank": 2,
      "points": 15110,
      "titles": 1,
      "hand": "Right",
      "surface": "Clay",
      "age": 21,
      "bestRank": 1,
      "wins": 25,
      "losses": 2,
      "height": "183 cm",
      "bio": "Carlos Alcaraz enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "novak-djokovic",
      "name": "Novak Djokovic",
      "country": "Serbia",
      "flag": "🇷🇸",
      "rank": 3,
      "points": 13060,
      "titles": 3,
      "hand": "Right",
      "surface": "Hard",
      "age": 22,
      "bestRank": 1,
      "wins": 24,
      "losses": 2,
      "height": "188 cm",
      "bio": "Novak Djokovic enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "rafael-nadal",
      "name": "Rafael Nadal",
      "country": "Spain",
      "flag": "🇪🇸",
      "rank": 4,
      "points": 7050,
      "titles": 2,
      "hand": "Left",
      "surface": "Clay",
      "age": 23,
      "bestRank": 1,
      "wins": 24,
      "losses": 2,
      "height": "193 cm",
      "bio": "Rafael Nadal enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "alexander-zverev",
      "name": "Alexander Zverev",
      "country": "Germany",
      "flag": "🇩🇪",
      "rank": 5,
      "points": 8690,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 24,
      "bestRank": 1,
      "wins": 24,
      "losses": 2,
      "height": "198 cm",
      "bio": "Alexander Zverev enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "alex-de-minaur",
      "name": "Alex de Minaur",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 6,
      "points": 5710,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "bestRank": 1,
      "wins": 24,
      "losses": 2,
      "height": "178 cm",
      "bio": "Alex de Minaur enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "ben-shelton",
      "name": "Ben Shelton",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 7,
      "points": 5560,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 26,
      "bestRank": 7,
      "wins": 23,
      "losses": 2,
      "height": "183 cm",
      "bio": "Ben Shelton enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "daniil-medvedev",
      "name": "Daniil Medvedev",
      "country": "Russia",
      "flag": "🇷🇺",
      "rank": 8,
      "points": 4780,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 27,
      "bestRank": 7,
      "wins": 23,
      "losses": 2,
      "height": "188 cm",
      "bio": "Daniil Medvedev enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "felix-auger-aliassime",
      "name": "Felix Auger-Aliassime",
      "country": "Canada",
      "flag": "🇨🇦",
      "rank": 9,
      "points": 4440,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "bestRank": 7,
      "wins": 23,
      "losses": 2,
      "height": "193 cm",
      "bio": "Felix Auger-Aliassime enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "taylor-fritz",
      "name": "Taylor Fritz",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 10,
      "points": 3915,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 29,
      "bestRank": 7,
      "wins": 23,
      "losses": 2,
      "height": "198 cm",
      "bio": "Taylor Fritz enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "flavio-cobolli",
      "name": "Flavio Cobolli",
      "country": "Italy",
      "flag": "🇮🇹",
      "rank": 11,
      "points": 3460,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "bestRank": 7,
      "wins": 22,
      "losses": 2,
      "height": "178 cm",
      "bio": "Flavio Cobolli enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "andrey-rublev",
      "name": "Andrey Rublev",
      "country": "Russia",
      "flag": "🇷🇺",
      "rank": 12,
      "points": 3420,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 31,
      "bestRank": 7,
      "wins": 22,
      "losses": 2,
      "height": "183 cm",
      "bio": "Andrey Rublev enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "alexander-bublik",
      "name": "Alexander Bublik",
      "country": "Kazakhstan",
      "flag": "🇰🇿",
      "rank": 13,
      "points": 2620,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 32,
      "bestRank": 13,
      "wins": 22,
      "losses": 2,
      "height": "188 cm",
      "bio": "Alexander Bublik enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "casper-ruud",
      "name": "Casper Ruud",
      "country": "Norway",
      "flag": "🇳🇴",
      "rank": 14,
      "points": 2425,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 33,
      "bestRank": 13,
      "wins": 22,
      "losses": 2,
      "height": "193 cm",
      "bio": "Casper Ruud enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jack-draper",
      "name": "Jack Draper",
      "country": "Great Britain",
      "flag": "🇬🇧",
      "rank": 15,
      "points": 2360,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 34,
      "bestRank": 13,
      "wins": 21,
      "losses": 2,
      "height": "198 cm",
      "bio": "Jack Draper enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "frances-tiafoe",
      "name": "Frances Tiafoe",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 16,
      "points": 2180,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 35,
      "bestRank": 13,
      "wins": 21,
      "losses": 2,
      "height": "178 cm",
      "bio": "Frances Tiafoe enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "arthur-fils",
      "name": "Arthur Fils",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 17,
      "points": 1890,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 36,
      "bestRank": 13,
      "wins": 21,
      "losses": 2,
      "height": "183 cm",
      "bio": "Arthur Fils enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "hubert-hurkacz",
      "name": "Hubert Hurkacz",
      "country": "Poland",
      "flag": "🇵🇱",
      "rank": 18,
      "points": 1880,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 37,
      "bestRank": 13,
      "wins": 21,
      "losses": 2,
      "height": "188 cm",
      "bio": "Hubert Hurkacz enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "holger-rune",
      "name": "Holger Rune",
      "country": "Denmark",
      "flag": "🇩🇰",
      "rank": 19,
      "points": 1825,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 38,
      "bestRank": 19,
      "wins": 20,
      "losses": 2,
      "height": "193 cm",
      "bio": "Holger Rune enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "tommy-paul",
      "name": "Tommy Paul",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 20,
      "points": 1790,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 39,
      "bestRank": 19,
      "wins": 20,
      "losses": 2,
      "height": "198 cm",
      "bio": "Tommy Paul enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "sebastian-korda",
      "name": "Sebastian Korda",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 21,
      "points": 1780,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 40,
      "bestRank": 19,
      "wins": 20,
      "losses": 2,
      "height": "178 cm",
      "bio": "Sebastian Korda enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "lorenzo-musetti",
      "name": "Lorenzo Musetti",
      "country": "Italy",
      "flag": "🇮🇹",
      "rank": 22,
      "points": 1720,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 41,
      "bestRank": 19,
      "wins": 20,
      "losses": 2,
      "height": "183 cm",
      "bio": "Lorenzo Musetti enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "juan-martin-del-potro",
      "name": "Juan Martin del Potro",
      "country": "Argentina",
      "flag": "🇦🇷",
      "rank": 23,
      "points": 1700,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 20,
      "bestRank": 19,
      "wins": 19,
      "losses": 2,
      "height": "188 cm",
      "bio": "Juan Martin del Potro enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "giovanni-mpetshi-perricard",
      "name": "Giovanni Mpetshi Perricard",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 24,
      "points": 1620,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 21,
      "bestRank": 19,
      "wins": 19,
      "losses": 2,
      "height": "193 cm",
      "bio": "Giovanni Mpetshi Perricard enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "ugo-humbert",
      "name": "Ugo Humbert",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 25,
      "points": 1460,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 22,
      "bestRank": 25,
      "wins": 19,
      "losses": 2,
      "height": "198 cm",
      "bio": "Ugo Humbert enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "matteo-berrettini",
      "name": "Matteo Berrettini",
      "country": "Italy",
      "flag": "🇮🇹",
      "rank": 26,
      "points": 1385,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 23,
      "bestRank": 25,
      "wins": 19,
      "losses": 2,
      "height": "178 cm",
      "bio": "Matteo Berrettini enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "karen-khachanov",
      "name": "Karen Khachanov",
      "country": "Russia",
      "flag": "🇷🇺",
      "rank": 27,
      "points": 1380,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 24,
      "bestRank": 25,
      "wins": 18,
      "losses": 2,
      "height": "183 cm",
      "bio": "Karen Khachanov enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "grigor-dimitrov",
      "name": "Grigor Dimitrov",
      "country": "Bulgaria",
      "flag": "🇧🇬",
      "rank": 28,
      "points": 1340,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "bestRank": 25,
      "wins": 18,
      "losses": 2,
      "height": "188 cm",
      "bio": "Grigor Dimitrov enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jakub-mensik",
      "name": "Jakub Mensik",
      "country": "Czechia",
      "flag": "🇨🇿",
      "rank": 29,
      "points": 1315,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 26,
      "bestRank": 25,
      "wins": 18,
      "losses": 2,
      "height": "193 cm",
      "bio": "Jakub Mensik enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "joao-fonseca",
      "name": "Joao Fonseca",
      "country": "Brazil",
      "flag": "🇧🇷",
      "rank": 30,
      "points": 1280,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 27,
      "bestRank": 25,
      "wins": 18,
      "losses": 2,
      "height": "198 cm",
      "bio": "Joao Fonseca enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jiri-lehecka",
      "name": "Jiri Lehecka",
      "country": "Czechia",
      "flag": "🇨🇿",
      "rank": 31,
      "points": 1250,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "bestRank": 31,
      "wins": 17,
      "losses": 2,
      "height": "178 cm",
      "bio": "Jiri Lehecka enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "denis-shapovalov",
      "name": "Denis Shapovalov",
      "country": "Canada",
      "flag": "🇨🇦",
      "rank": 32,
      "points": 1210,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 29,
      "bestRank": 31,
      "wins": 17,
      "losses": 2,
      "height": "183 cm",
      "bio": "Denis Shapovalov enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "tallon-griekspoor",
      "name": "Tallon Griekspoor",
      "country": "Netherlands",
      "flag": "🇳🇱",
      "rank": 33,
      "points": 1160,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "bestRank": 31,
      "wins": 17,
      "losses": 3,
      "height": "188 cm",
      "bio": "Tallon Griekspoor enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "cameron-norrie",
      "name": "Cameron Norrie",
      "country": "Great Britain",
      "flag": "🇬🇧",
      "rank": 34,
      "points": 1125,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 31,
      "bestRank": 31,
      "wins": 17,
      "losses": 3,
      "height": "193 cm",
      "bio": "Cameron Norrie enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "francisco-cerundolo",
      "name": "Francisco Cerundolo",
      "country": "Argentina",
      "flag": "🇦🇷",
      "rank": 35,
      "points": 1090,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 32,
      "bestRank": 31,
      "wins": 16,
      "losses": 3,
      "height": "198 cm",
      "bio": "Francisco Cerundolo enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "nicolas-jarry",
      "name": "Nicolas Jarry",
      "country": "Chile",
      "flag": "🇨🇱",
      "rank": 36,
      "points": 1060,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 33,
      "bestRank": 31,
      "wins": 16,
      "losses": 3,
      "height": "178 cm",
      "bio": "Nicolas Jarry enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "stefanos-tsitsipas",
      "name": "Stefanos Tsitsipas",
      "country": "Greece",
      "flag": "🇬🇷",
      "rank": 37,
      "points": 1050,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 34,
      "bestRank": 37,
      "wins": 16,
      "losses": 3,
      "height": "183 cm",
      "bio": "Stefanos Tsitsipas enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "miomir-kecmanovic",
      "name": "Miomir Kecmanovic",
      "country": "Serbia",
      "flag": "🇷🇸",
      "rank": 38,
      "points": 1005,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 35,
      "bestRank": 37,
      "wins": 16,
      "losses": 3,
      "height": "188 cm",
      "bio": "Miomir Kecmanovic enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jordan-thompson",
      "name": "Jordan Thompson",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 39,
      "points": 980,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 36,
      "bestRank": 37,
      "wins": 15,
      "losses": 3,
      "height": "193 cm",
      "bio": "Jordan Thompson enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "thanasi-kokkinakis",
      "name": "Thanasi Kokkinakis",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 40,
      "points": 980,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 37,
      "bestRank": 37,
      "wins": 15,
      "losses": 3,
      "height": "198 cm",
      "bio": "Thanasi Kokkinakis enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "roger-federer",
      "name": "Roger Federer",
      "country": "Switzerland",
      "flag": "🇨🇭",
      "rank": 41,
      "points": 950,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 38,
      "bestRank": 37,
      "wins": 15,
      "losses": 3,
      "height": "178 cm",
      "bio": "Roger Federer enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "gael-monfils",
      "name": "Gael Monfils",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 42,
      "points": 930,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 39,
      "bestRank": 37,
      "wins": 15,
      "losses": 3,
      "height": "183 cm",
      "bio": "Gael Monfils enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "stan-wawrinka",
      "name": "Stan Wawrinka",
      "country": "Switzerland",
      "flag": "🇨🇭",
      "rank": 43,
      "points": 910,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 40,
      "bestRank": 43,
      "wins": 14,
      "losses": 3,
      "height": "188 cm",
      "bio": "Stan Wawrinka enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "alexei-popyrin",
      "name": "Alexei Popyrin",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 44,
      "points": 900,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 41,
      "bestRank": 43,
      "wins": 14,
      "losses": 4,
      "height": "193 cm",
      "bio": "Alexei Popyrin enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "kei-nishikori",
      "name": "Kei Nishikori",
      "country": "Japan",
      "flag": "🇯🇵",
      "rank": 45,
      "points": 890,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 20,
      "bestRank": 43,
      "wins": 14,
      "losses": 4,
      "height": "198 cm",
      "bio": "Kei Nishikori enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "andy-murray",
      "name": "Andy Murray",
      "country": "Great Britain",
      "flag": "🇬🇧",
      "rank": 46,
      "points": 870,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 21,
      "bestRank": 43,
      "wins": 14,
      "losses": 4,
      "height": "178 cm",
      "bio": "Andy Murray enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "milos-raonic",
      "name": "Milos Raonic",
      "country": "Canada",
      "flag": "🇨🇦",
      "rank": 47,
      "points": 850,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 22,
      "bestRank": 43,
      "wins": 13,
      "losses": 4,
      "height": "183 cm",
      "bio": "Milos Raonic enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "kevin-anderson",
      "name": "Kevin Anderson",
      "country": "South Africa",
      "flag": "🇿🇦",
      "rank": 48,
      "points": 830,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 23,
      "bestRank": 43,
      "wins": 13,
      "losses": 4,
      "height": "188 cm",
      "bio": "Kevin Anderson enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "richard-gasquet",
      "name": "Richard Gasquet",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 49,
      "points": 810,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 24,
      "bestRank": 49,
      "wins": 13,
      "losses": 4,
      "height": "193 cm",
      "bio": "Richard Gasquet enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jan-lennard-struff",
      "name": "Jan-Lennard Struff",
      "country": "Germany",
      "flag": "🇩🇪",
      "rank": 50,
      "points": 804,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "bestRank": 49,
      "wins": 13,
      "losses": 4,
      "height": "198 cm",
      "bio": "Jan-Lennard Struff enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "reilly-opelka",
      "name": "Reilly Opelka",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 51,
      "points": 790,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 26,
      "bestRank": 49,
      "wins": 12,
      "losses": 4,
      "height": "178 cm",
      "bio": "Reilly Opelka enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "nick-kyrgios",
      "name": "Nick Kyrgios",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 52,
      "points": 775,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 27,
      "bestRank": 49,
      "wins": 12,
      "losses": 4,
      "height": "183 cm",
      "bio": "Nick Kyrgios enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "roberto-bautista-agut",
      "name": "Roberto Bautista Agut",
      "country": "Spain",
      "flag": "🇪🇸",
      "rank": 53,
      "points": 760,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "bestRank": 49,
      "wins": 12,
      "losses": 4,
      "height": "188 cm",
      "bio": "Roberto Bautista Agut enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "marin-cilic",
      "name": "Marin Cilic",
      "country": "Croatia",
      "flag": "🇭🇷",
      "rank": 54,
      "points": 745,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 29,
      "bestRank": 49,
      "wins": 12,
      "losses": 4,
      "height": "193 cm",
      "bio": "Marin Cilic enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "david-goffin",
      "name": "David Goffin",
      "country": "Belgium",
      "flag": "🇧🇪",
      "rank": 55,
      "points": 730,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "bestRank": 55,
      "wins": 11,
      "losses": 5,
      "height": "198 cm",
      "bio": "David Goffin enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "borna-coric",
      "name": "Borna Coric",
      "country": "Croatia",
      "flag": "🇭🇷",
      "rank": 56,
      "points": 715,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 31,
      "bestRank": 55,
      "wins": 11,
      "losses": 5,
      "height": "178 cm",
      "bio": "Borna Coric enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "fabio-fognini",
      "name": "Fabio Fognini",
      "country": "Italy",
      "flag": "🇮🇹",
      "rank": 57,
      "points": 700,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 32,
      "bestRank": 55,
      "wins": 11,
      "losses": 5,
      "height": "183 cm",
      "bio": "Fabio Fognini enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "dominic-thiem",
      "name": "Dominic Thiem",
      "country": "Austria",
      "flag": "🇦🇹",
      "rank": 58,
      "points": 685,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 33,
      "bestRank": 55,
      "wins": 11,
      "losses": 5,
      "height": "188 cm",
      "bio": "Dominic Thiem enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jo-wilfried-tsonga",
      "name": "Jo-Wilfried Tsonga",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 59,
      "points": 670,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 34,
      "bestRank": 55,
      "wins": 10,
      "losses": 5,
      "height": "193 cm",
      "bio": "Jo-Wilfried Tsonga enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "john-isner",
      "name": "John Isner",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 60,
      "points": 655,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 35,
      "bestRank": 55,
      "wins": 10,
      "losses": 5,
      "height": "198 cm",
      "bio": "John Isner enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "tomas-berdych",
      "name": "Tomas Berdych",
      "country": "Czechia",
      "flag": "🇨🇿",
      "rank": 61,
      "points": 640,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 36,
      "bestRank": 61,
      "wins": 10,
      "losses": 5,
      "height": "178 cm",
      "bio": "Tomas Berdych enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jack-sock",
      "name": "Jack Sock",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 62,
      "points": 625,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 37,
      "bestRank": 61,
      "wins": 10,
      "losses": 5,
      "height": "183 cm",
      "bio": "Jack Sock enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "sam-querrey",
      "name": "Sam Querrey",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 63,
      "points": 610,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 38,
      "bestRank": 61,
      "wins": 9,
      "losses": 5,
      "height": "188 cm",
      "bio": "Sam Querrey enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "bernard-tomic",
      "name": "Bernard Tomic",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 64,
      "points": 595,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 39,
      "bestRank": 61,
      "wins": 9,
      "losses": 5,
      "height": "193 cm",
      "bio": "Bernard Tomic enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "learner-tien",
      "name": "Learner Tien",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 65,
      "points": 560,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 40,
      "bestRank": 61,
      "wins": 9,
      "losses": 5,
      "height": "198 cm",
      "bio": "Learner Tien enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "alex-michelsen",
      "name": "Alex Michelsen",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 66,
      "points": 545,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 41,
      "bestRank": 61,
      "wins": 9,
      "losses": 6,
      "height": "178 cm",
      "bio": "Alex Michelsen enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "dino-prizmic",
      "name": "Dino Prizmic",
      "country": "Croatia",
      "flag": "🇭🇷",
      "rank": 67,
      "points": 530,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 20,
      "bestRank": 67,
      "wins": 8,
      "losses": 6,
      "height": "183 cm",
      "bio": "Dino Prizmic enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "martin-landaluce",
      "name": "Martin Landaluce",
      "country": "Spain",
      "flag": "🇪🇸",
      "rank": 68,
      "points": 515,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 21,
      "bestRank": 67,
      "wins": 8,
      "losses": 6,
      "height": "188 cm",
      "bio": "Martin Landaluce enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "christopher-eubanks",
      "name": "Christopher Eubanks",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 69,
      "points": 500,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 22,
      "bestRank": 67,
      "wins": 8,
      "losses": 6,
      "height": "193 cm",
      "bio": "Christopher Eubanks enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "alexander-blockx",
      "name": "Alexander Blockx",
      "country": "Belgium",
      "flag": "🇧🇪",
      "rank": 70,
      "points": 485,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 23,
      "bestRank": 67,
      "wins": 8,
      "losses": 6,
      "height": "198 cm",
      "bio": "Alexander Blockx enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "kyle-edmund",
      "name": "Kyle Edmund",
      "country": "Great Britain",
      "flag": "🇬🇧",
      "rank": 71,
      "points": 470,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 24,
      "bestRank": 67,
      "wins": 7,
      "losses": 6,
      "height": "178 cm",
      "bio": "Kyle Edmund enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "daniel-evans",
      "name": "Daniel Evans",
      "country": "Great Britain",
      "flag": "🇬🇧",
      "rank": 72,
      "points": 455,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "bestRank": 67,
      "wins": 7,
      "losses": 6,
      "height": "183 cm",
      "bio": "Daniel Evans enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "aleksandar-vukic",
      "name": "Aleksandar Vukic",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 73,
      "points": 440,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 26,
      "bestRank": 73,
      "wins": 7,
      "losses": 6,
      "height": "188 cm",
      "bio": "Aleksandar Vukic enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "federico-coria",
      "name": "Federico Coria",
      "country": "Argentina",
      "flag": "🇦🇷",
      "rank": 74,
      "points": 425,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 27,
      "bestRank": 73,
      "wins": 7,
      "losses": 6,
      "height": "193 cm",
      "bio": "Federico Coria enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "nuno-borges",
      "name": "Nuno Borges",
      "country": "Portugal",
      "flag": "🇵🇹",
      "rank": 75,
      "points": 410,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "bestRank": 73,
      "wins": 6,
      "losses": 6,
      "height": "198 cm",
      "bio": "Nuno Borges enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "thiago-seyboth-wild",
      "name": "Thiago Seyboth Wild",
      "country": "Brazil",
      "flag": "🇧🇷",
      "rank": 76,
      "points": 395,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 29,
      "bestRank": 73,
      "wins": 6,
      "losses": 6,
      "height": "178 cm",
      "bio": "Thiago Seyboth Wild enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "diego-schwartzman",
      "name": "Diego Schwartzman",
      "country": "Argentina",
      "flag": "🇦🇷",
      "rank": 77,
      "points": 380,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "bestRank": 73,
      "wins": 6,
      "losses": 7,
      "height": "183 cm",
      "bio": "Diego Schwartzman enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "matthew-ebden",
      "name": "Matthew Ebden",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 78,
      "points": 365,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 31,
      "bestRank": 73,
      "wins": 6,
      "losses": 7,
      "height": "188 cm",
      "bio": "Matthew Ebden enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "dominik-koepfer",
      "name": "Dominik Koepfer",
      "country": "Germany",
      "flag": "🇩🇪",
      "rank": 79,
      "points": 350,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 32,
      "bestRank": 79,
      "wins": 5,
      "losses": 7,
      "height": "193 cm",
      "bio": "Dominik Koepfer enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "mariano-navone",
      "name": "Mariano Navone",
      "country": "Argentina",
      "flag": "🇦🇷",
      "rank": 80,
      "points": 335,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 33,
      "bestRank": 79,
      "wins": 5,
      "losses": 7,
      "height": "198 cm",
      "bio": "Mariano Navone enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "tomas-martin-etcheverry",
      "name": "Tomas Martin Etcheverry",
      "country": "Argentina",
      "flag": "🇦🇷",
      "rank": 81,
      "points": 320,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 34,
      "bestRank": 79,
      "wins": 5,
      "losses": 7,
      "height": "178 cm",
      "bio": "Tomas Martin Etcheverry enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "camilo-ugo-carabelli",
      "name": "Camilo Ugo Carabelli",
      "country": "Argentina",
      "flag": "🇦🇷",
      "rank": 82,
      "points": 305,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 35,
      "bestRank": 79,
      "wins": 5,
      "losses": 7,
      "height": "183 cm",
      "bio": "Camilo Ugo Carabelli enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "jason-kubler",
      "name": "Jason Kubler",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 83,
      "points": 290,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 36,
      "bestRank": 79,
      "wins": 4,
      "losses": 7,
      "height": "188 cm",
      "bio": "Jason Kubler enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "mackenzie-mcdonald",
      "name": "Mackenzie McDonald",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 84,
      "points": 275,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 37,
      "bestRank": 79,
      "wins": 4,
      "losses": 7,
      "height": "193 cm",
      "bio": "Mackenzie McDonald enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "max-purcell",
      "name": "Max Purcell",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 85,
      "points": 260,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 38,
      "bestRank": 85,
      "wins": 4,
      "losses": 7,
      "height": "198 cm",
      "bio": "Max Purcell enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "yoshihito-nishioka",
      "name": "Yoshihito Nishioka",
      "country": "Japan",
      "flag": "🇯🇵",
      "rank": 86,
      "points": 245,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 39,
      "bestRank": 85,
      "wins": 4,
      "losses": 7,
      "height": "178 cm",
      "bio": "Yoshihito Nishioka enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "j-j-wolf",
      "name": "J.J. Wolf",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 87,
      "points": 230,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 40,
      "bestRank": 85,
      "wins": 4,
      "losses": 7,
      "height": "183 cm",
      "bio": "J.J. Wolf enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "luca-van-assche",
      "name": "Luca Van Assche",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 88,
      "points": 215,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 41,
      "bestRank": 85,
      "wins": 4,
      "losses": 8,
      "height": "188 cm",
      "bio": "Luca Van Assche enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "christopher-o-connell",
      "name": "Christopher O'Connell",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 89,
      "points": 200,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 20,
      "bestRank": 85,
      "wins": 4,
      "losses": 8,
      "height": "193 cm",
      "bio": "Christopher O'Connell enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "rinky-hijikata",
      "name": "Rinky Hijikata",
      "country": "Australia",
      "flag": "🇦🇺",
      "rank": 90,
      "points": 185,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 21,
      "bestRank": 85,
      "wins": 4,
      "losses": 8,
      "height": "198 cm",
      "bio": "Rinky Hijikata enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "taro-daniel",
      "name": "Taro Daniel",
      "country": "Japan",
      "flag": "🇯🇵",
      "rank": 91,
      "points": 170,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 22,
      "bestRank": 91,
      "wins": 4,
      "losses": 8,
      "height": "178 cm",
      "bio": "Taro Daniel enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "arthur-rinderknech",
      "name": "Arthur Rinderknech",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 92,
      "points": 155,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 23,
      "bestRank": 91,
      "wins": 4,
      "losses": 8,
      "height": "183 cm",
      "bio": "Arthur Rinderknech enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "yibing-wu",
      "name": "Yibing Wu",
      "country": "China",
      "flag": "🇨🇳",
      "rank": 93,
      "points": 140,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 24,
      "bestRank": 91,
      "wins": 4,
      "losses": 8,
      "height": "188 cm",
      "bio": "Yibing Wu enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "michael-mmoh",
      "name": "Michael Mmoh",
      "country": "USA",
      "flag": "🇺🇸",
      "rank": 94,
      "points": 125,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "bestRank": 91,
      "wins": 4,
      "losses": 8,
      "height": "193 cm",
      "bio": "Michael Mmoh enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "zizou-bergs",
      "name": "Zizou Bergs",
      "country": "Belgium",
      "flag": "🇧🇪",
      "rank": 95,
      "points": 110,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 26,
      "bestRank": 91,
      "wins": 4,
      "losses": 8,
      "height": "198 cm",
      "bio": "Zizou Bergs enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    },
    {
      "id": "benoit-paire",
      "name": "Benoit Paire",
      "country": "France",
      "flag": "🇫🇷",
      "rank": 96,
      "points": 95,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 27,
      "bestRank": 91,
      "wins": 4,
      "losses": 8,
      "height": "178 cm",
      "bio": "Benoit Paire enters ATP Universe Pro 1.0 as part of the 96-player 2026 roster."
    }
  ],
  "tournaments": [
    {
      "name": "Australian Open",
      "surface": "Hard",
      "category": "Grand Slam",
      "champion": "Novak Djokovic",
      "runner": "Carlos Alcaraz",
      "score": "6-7(6), 7-5, 6-4, 3-6, 6-3",
      "status": "Completed",
      "mvp": "Rafael Nadal"
    },
    {
      "name": "Indian Wells",
      "surface": "Hard",
      "category": "Masters 1000",
      "champion": "Novak Djokovic",
      "runner": "Carlos Alcaraz",
      "score": "6-4, 4-6, 7-6(5)",
      "status": "Completed",
      "mvp": "Novak Djokovic"
    },
    {
      "name": "Miami",
      "surface": "Hard",
      "category": "Masters 1000",
      "champion": "Carlos Alcaraz",
      "runner": "Novak Djokovic",
      "score": "4-6, 7-5, 6-3",
      "status": "Completed",
      "mvp": "Carlos Alcaraz"
    },
    {
      "name": "Monte-Carlo",
      "surface": "Clay",
      "category": "Masters 1000",
      "champion": "Rafael Nadal",
      "runner": "Carlos Alcaraz",
      "score": "6-4, 3-6, 6-3",
      "status": "Completed",
      "mvp": "Rafael Nadal"
    },
    {
      "name": "Madrid",
      "surface": "Clay",
      "category": "Masters 1000",
      "champion": "Novak Djokovic",
      "runner": "Rafael Nadal",
      "score": "4-6, 7-5, 6-4",
      "status": "Completed",
      "mvp": "Novak Djokovic"
    },
    {
      "name": "Rome",
      "surface": "Clay",
      "category": "Masters 1000",
      "champion": "Rafael Nadal",
      "runner": "Novak Djokovic",
      "score": "6-3, 4-6, 6-4",
      "status": "Completed",
      "mvp": "Rafael Nadal"
    },
    {
      "name": "Roland Garros",
      "surface": "Clay",
      "category": "Grand Slam",
      "champion": "",
      "runner": "",
      "score": "",
      "status": "Next",
      "mvp": ""
    }
  ],
  "matches": [
    {
      "tournament": "Australian Open",
      "round": "R16",
      "winner": "Rafael Nadal",
      "loser": "Jannik Sinner",
      "score": "7-6(5), 6-4, 7-5"
    },
    {
      "tournament": "Australian Open",
      "round": "QF",
      "winner": "Novak Djokovic",
      "loser": "Matteo Berrettini",
      "score": "6-7(5), 6-3, 6-4, 7-6(6)"
    },
    {
      "tournament": "Australian Open",
      "round": "SF",
      "winner": "Novak Djokovic",
      "loser": "Rafael Nadal",
      "score": "4-6, 7-6(5), 6-3, 7-5"
    },
    {
      "tournament": "Australian Open",
      "round": "Final",
      "winner": "Novak Djokovic",
      "loser": "Carlos Alcaraz",
      "score": "6-7(6), 7-5, 6-4, 3-6, 6-3"
    }
  ],
  "news": [
    {
      "title": "Roland Garros is next",
      "body": "Sinner keeps No.1, Djokovic leads the season, and Nadal arrives with clay momentum."
    }
  ]
};