const DATA = {
  "players": [
    {
      "id": "jannik-sinner",
      "name": "Jannik Sinner",
      "country": "Italy",
      "rank": 1,
      "points": 15250,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 23,
      "wins": 38,
      "losses": 12,
      "bestRank": 1,
      "status": "Active"
    },
    {
      "id": "carlos-alcaraz",
      "name": "Carlos Alcaraz",
      "country": "Spain",
      "rank": 2,
      "points": 15110,
      "titles": 1,
      "hand": "Right",
      "surface": "Clay",
      "age": 22,
      "wins": 42,
      "losses": 10,
      "bestRank": 2,
      "status": "Active"
    },
    {
      "id": "novak-djokovic",
      "name": "Novak Djokovic",
      "country": "Serbia",
      "rank": 3,
      "points": 13060,
      "titles": 3,
      "hand": "Right",
      "surface": "Hard",
      "age": 38,
      "wins": 42,
      "losses": 14,
      "bestRank": 2,
      "status": "Active"
    },
    {
      "id": "rafael-nadal",
      "name": "Rafael Nadal",
      "country": "Spain",
      "rank": 4,
      "points": 7050,
      "titles": 2,
      "hand": "Left",
      "surface": "Clay",
      "age": 39,
      "wins": 42,
      "losses": 5,
      "bestRank": 4,
      "status": "Active"
    },
    {
      "id": "alexander-zverev",
      "name": "Alexander Zverev",
      "country": "Germany",
      "rank": 5,
      "points": 8690,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "wins": 34,
      "losses": 15,
      "bestRank": 3,
      "status": "Active"
    },
    {
      "id": "alex-de-minaur",
      "name": "Alex de Minaur",
      "country": "Australia",
      "rank": 6,
      "points": 5710,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 27,
      "wins": 37,
      "losses": 3,
      "bestRank": 1,
      "status": "Active"
    },
    {
      "id": "ben-shelton",
      "name": "Ben Shelton",
      "country": "USA",
      "rank": 7,
      "points": 5560,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 23,
      "wins": 36,
      "losses": 3,
      "bestRank": 2,
      "status": "Active"
    },
    {
      "id": "daniil-medvedev",
      "name": "Daniil Medvedev",
      "country": "Russia",
      "rank": 8,
      "points": 4780,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "wins": 31,
      "losses": 9,
      "bestRank": 3,
      "status": "Active"
    },
    {
      "id": "felix-auger-aliassime",
      "name": "Felix Auger-Aliassime",
      "country": "Canada",
      "rank": 9,
      "points": 4440,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "wins": 35,
      "losses": 14,
      "bestRank": 9,
      "status": "Active"
    },
    {
      "id": "taylor-fritz",
      "name": "Taylor Fritz",
      "country": "USA",
      "rank": 10,
      "points": 3915,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "wins": 35,
      "losses": 8,
      "bestRank": 5,
      "status": "Active"
    },
    {
      "id": "flavio-cobolli",
      "name": "Flavio Cobolli",
      "country": "Italy",
      "rank": 11,
      "points": 3460,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 24,
      "wins": 29,
      "losses": 7,
      "bestRank": 10,
      "status": "Active"
    },
    {
      "id": "andrey-rublev",
      "name": "Andrey Rublev",
      "country": "Russia",
      "rank": 12,
      "points": 3420,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "wins": 33,
      "losses": 16,
      "bestRank": 5,
      "status": "Active"
    },
    {
      "id": "alexander-bublik",
      "name": "Alexander Bublik",
      "country": "Kazakhstan",
      "rank": 13,
      "points": 2620,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 28,
      "wins": 29,
      "losses": 12,
      "bestRank": 1,
      "status": "Active"
    },
    {
      "id": "casper-ruud",
      "name": "Casper Ruud",
      "country": "Norway",
      "rank": 14,
      "points": 2425,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 27,
      "wins": 28,
      "losses": 12,
      "bestRank": 8,
      "status": "Active"
    },
    {
      "id": "jack-draper",
      "name": "Jack Draper",
      "country": "Great Britain",
      "rank": 15,
      "points": 2360,
      "titles": 0,
      "hand": "Left",
      "surface": "Grass",
      "age": 24,
      "wins": 31,
      "losses": 11,
      "bestRank": 1,
      "status": "Active"
    },
    {
      "id": "frances-tiafoe",
      "name": "Frances Tiafoe",
      "country": "USA",
      "rank": 16,
      "points": 2180,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "wins": 28,
      "losses": 5,
      "bestRank": 12,
      "status": "Active"
    },
    {
      "id": "arthur-fils",
      "name": "Arthur Fils",
      "country": "France",
      "rank": 17,
      "points": 1890,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 22,
      "wins": 32,
      "losses": 4,
      "bestRank": 1,
      "status": "Active"
    },
    {
      "id": "hubert-hurkacz",
      "name": "Hubert Hurkacz",
      "country": "Poland",
      "rank": 18,
      "points": 1880,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 29,
      "wins": 31,
      "losses": 7,
      "bestRank": 9,
      "status": "Active"
    },
    {
      "id": "holger-rune",
      "name": "Holger Rune",
      "country": "Denmark",
      "rank": 19,
      "points": 1825,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 23,
      "wins": 33,
      "losses": 7,
      "bestRank": 8,
      "status": "Active"
    },
    {
      "id": "tommy-paul",
      "name": "Tommy Paul",
      "country": "USA",
      "rank": 20,
      "points": 1790,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 29,
      "wins": 30,
      "losses": 9,
      "bestRank": 15,
      "status": "Active"
    },
    {
      "id": "sebastian-korda",
      "name": "Sebastian Korda",
      "country": "USA",
      "rank": 21,
      "points": 1780,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "wins": 27,
      "losses": 8,
      "bestRank": 17,
      "status": "Active"
    },
    {
      "id": "lorenzo-musetti",
      "name": "Lorenzo Musetti",
      "country": "Italy",
      "rank": 22,
      "points": 1720,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 24,
      "wins": 26,
      "losses": 11,
      "bestRank": 7,
      "status": "Active"
    },
    {
      "id": "juan-martin-del-potro",
      "name": "Juan Martin del Potro",
      "country": "Argentina",
      "rank": 23,
      "points": 1700,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 37,
      "wins": 29,
      "losses": 14,
      "bestRank": 18,
      "status": "Active"
    },
    {
      "id": "giovanni-mpetshi-perricard",
      "name": "Giovanni Mpetshi Perricard",
      "country": "France",
      "rank": 24,
      "points": 1620,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 23,
      "wins": 26,
      "losses": 10,
      "bestRank": 12,
      "status": "Active"
    },
    {
      "id": "ugo-humbert",
      "name": "Ugo Humbert",
      "country": "France",
      "rank": 25,
      "points": 1460,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 27,
      "wins": 30,
      "losses": 7,
      "bestRank": 5,
      "status": "Active"
    },
    {
      "id": "matteo-berrettini",
      "name": "Matteo Berrettini",
      "country": "Italy",
      "rank": 26,
      "points": 1385,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 30,
      "wins": 31,
      "losses": 14,
      "bestRank": 24,
      "status": "Active"
    },
    {
      "id": "karen-khachanov",
      "name": "Karen Khachanov",
      "country": "Russia",
      "rank": 27,
      "points": 1380,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "wins": 30,
      "losses": 16,
      "bestRank": 4,
      "status": "Active"
    },
    {
      "id": "grigor-dimitrov",
      "name": "Grigor Dimitrov",
      "country": "Bulgaria",
      "rank": 28,
      "points": 1340,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 35,
      "wins": 24,
      "losses": 12,
      "bestRank": 5,
      "status": "Active"
    },
    {
      "id": "jakub-mensik",
      "name": "Jakub Mensik",
      "country": "Czechia",
      "rank": 29,
      "points": 1315,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 20,
      "wins": 27,
      "losses": 15,
      "bestRank": 28,
      "status": "Active"
    },
    {
      "id": "joao-fonseca",
      "name": "Joao Fonseca",
      "country": "Brazil",
      "rank": 30,
      "points": 1280,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 19,
      "wins": 30,
      "losses": 9,
      "bestRank": 18,
      "status": "Active"
    },
    {
      "id": "jiri-lehecka",
      "name": "Jiri Lehecka",
      "country": "Czechia",
      "rank": 31,
      "points": 1250,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 24,
      "wins": 28,
      "losses": 6,
      "bestRank": 7,
      "status": "Active"
    },
    {
      "id": "denis-shapovalov",
      "name": "Denis Shapovalov",
      "country": "Canada",
      "rank": 32,
      "points": 1210,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 27,
      "wins": 25,
      "losses": 15,
      "bestRank": 18,
      "status": "Active"
    },
    {
      "id": "tallon-griekspoor",
      "name": "Tallon Griekspoor",
      "country": "Netherlands",
      "rank": 33,
      "points": 1160,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 29,
      "wins": 24,
      "losses": 3,
      "bestRank": 2,
      "status": "Active"
    },
    {
      "id": "cameron-norrie",
      "name": "Cameron Norrie",
      "country": "Great Britain",
      "rank": 34,
      "points": 1125,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 30,
      "wins": 23,
      "losses": 6,
      "bestRank": 14,
      "status": "Active"
    },
    {
      "id": "francisco-cerundolo",
      "name": "Francisco Cerundolo",
      "country": "Argentina",
      "rank": 35,
      "points": 1090,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 27,
      "wins": 22,
      "losses": 10,
      "bestRank": 23,
      "status": "Active"
    },
    {
      "id": "nicolas-jarry",
      "name": "Nicolas Jarry",
      "country": "Chile",
      "rank": 36,
      "points": 1060,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 30,
      "wins": 26,
      "losses": 14,
      "bestRank": 3,
      "status": "Active"
    },
    {
      "id": "stefanos-tsitsipas",
      "name": "Stefanos Tsitsipas",
      "country": "Greece",
      "rank": 37,
      "points": 1050,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 27,
      "wins": 24,
      "losses": 7,
      "bestRank": 6,
      "status": "Active"
    },
    {
      "id": "miomir-kecmanovic",
      "name": "Miomir Kecmanovic",
      "country": "Serbia",
      "rank": 38,
      "points": 1005,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 26,
      "wins": 21,
      "losses": 8,
      "bestRank": 25,
      "status": "Active"
    },
    {
      "id": "jordan-thompson",
      "name": "Jordan Thompson",
      "country": "Australia",
      "rank": 39,
      "points": 980,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 32,
      "wins": 27,
      "losses": 12,
      "bestRank": 11,
      "status": "Active"
    },
    {
      "id": "thanasi-kokkinakis",
      "name": "Thanasi Kokkinakis",
      "country": "Australia",
      "rank": 40,
      "points": 980,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "wins": 22,
      "losses": 7,
      "bestRank": 4,
      "status": "Active"
    },
    {
      "id": "roger-federer",
      "name": "Roger Federer",
      "country": "Switzerland",
      "rank": 41,
      "points": 950,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 44,
      "wins": 20,
      "losses": 7,
      "bestRank": 37,
      "status": "Active"
    },
    {
      "id": "gael-monfils",
      "name": "Gael Monfils",
      "country": "France",
      "rank": 42,
      "points": 930,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 39,
      "wins": 19,
      "losses": 5,
      "bestRank": 16,
      "status": "Active"
    },
    {
      "id": "stan-wawrinka",
      "name": "Stan Wawrinka",
      "country": "Switzerland",
      "rank": 43,
      "points": 910,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 41,
      "wins": 21,
      "losses": 6,
      "bestRank": 11,
      "status": "Active"
    },
    {
      "id": "alexei-popyrin",
      "name": "Alexei Popyrin",
      "country": "Australia",
      "rank": 44,
      "points": 900,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 26,
      "wins": 25,
      "losses": 5,
      "bestRank": 18,
      "status": "Active"
    },
    {
      "id": "kei-nishikori",
      "name": "Kei Nishikori",
      "country": "Japan",
      "rank": 45,
      "points": 890,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 36,
      "wins": 21,
      "losses": 5,
      "bestRank": 22,
      "status": "Active"
    },
    {
      "id": "andy-murray",
      "name": "Andy Murray",
      "country": "Great Britain",
      "rank": 46,
      "points": 870,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 39,
      "wins": 20,
      "losses": 8,
      "bestRank": 41,
      "status": "Active"
    },
    {
      "id": "milos-raonic",
      "name": "Milos Raonic",
      "country": "Canada",
      "rank": 47,
      "points": 850,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 35,
      "wins": 19,
      "losses": 6,
      "bestRank": 40,
      "status": "Active"
    },
    {
      "id": "kevin-anderson",
      "name": "Kevin Anderson",
      "country": "South Africa",
      "rank": 48,
      "points": 830,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 40,
      "wins": 24,
      "losses": 3,
      "bestRank": 19,
      "status": "Active"
    },
    {
      "id": "richard-gasquet",
      "name": "Richard Gasquet",
      "country": "France",
      "rank": 49,
      "points": 810,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 40,
      "wins": 18,
      "losses": 14,
      "bestRank": 13,
      "status": "Active"
    },
    {
      "id": "jan-lennard-struff",
      "name": "Jan-Lennard Struff",
      "country": "Germany",
      "rank": 50,
      "points": 804,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 36,
      "wins": 22,
      "losses": 11,
      "bestRank": 44,
      "status": "Active"
    },
    {
      "id": "reilly-opelka",
      "name": "Reilly Opelka",
      "country": "USA",
      "rank": 51,
      "points": 790,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "wins": 20,
      "losses": 5,
      "bestRank": 25,
      "status": "Active"
    },
    {
      "id": "nick-kyrgios",
      "name": "Nick Kyrgios",
      "country": "Australia",
      "rank": 52,
      "points": 775,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 31,
      "wins": 19,
      "losses": 12,
      "bestRank": 33,
      "status": "Active"
    },
    {
      "id": "roberto-bautista-agut",
      "name": "Roberto Bautista Agut",
      "country": "Spain",
      "rank": 53,
      "points": 760,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 38,
      "wins": 19,
      "losses": 13,
      "bestRank": 15,
      "status": "Active"
    },
    {
      "id": "marin-cilic",
      "name": "Marin Cilic",
      "country": "Croatia",
      "rank": 54,
      "points": 745,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 37,
      "wins": 16,
      "losses": 10,
      "bestRank": 48,
      "status": "Active"
    },
    {
      "id": "david-goffin",
      "name": "David Goffin",
      "country": "Belgium",
      "rank": 55,
      "points": 730,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 35,
      "wins": 21,
      "losses": 4,
      "bestRank": 53,
      "status": "Active"
    },
    {
      "id": "borna-coric",
      "name": "Borna Coric",
      "country": "Croatia",
      "rank": 56,
      "points": 715,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 29,
      "wins": 20,
      "losses": 12,
      "bestRank": 35,
      "status": "Active"
    },
    {
      "id": "fabio-fognini",
      "name": "Fabio Fognini",
      "country": "Italy",
      "rank": 57,
      "points": 700,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 39,
      "wins": 17,
      "losses": 5,
      "bestRank": 50,
      "status": "Universe"
    },
    {
      "id": "dominic-thiem",
      "name": "Dominic Thiem",
      "country": "Austria",
      "rank": 58,
      "points": 685,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 32,
      "wins": 14,
      "losses": 3,
      "bestRank": 49,
      "status": "Universe"
    },
    {
      "id": "jo-wilfried-tsonga",
      "name": "Jo-Wilfried Tsonga",
      "country": "France",
      "rank": 59,
      "points": 670,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 41,
      "wins": 13,
      "losses": 11,
      "bestRank": 21,
      "status": "Universe"
    },
    {
      "id": "john-isner",
      "name": "John Isner",
      "country": "USA",
      "rank": 60,
      "points": 655,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 41,
      "wins": 16,
      "losses": 5,
      "bestRank": 25,
      "status": "Universe"
    },
    {
      "id": "tomas-berdych",
      "name": "Tomas Berdych",
      "country": "Czechia",
      "rank": 61,
      "points": 640,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 40,
      "wins": 19,
      "losses": 13,
      "bestRank": 1,
      "status": "Universe"
    },
    {
      "id": "jack-sock",
      "name": "Jack Sock",
      "country": "USA",
      "rank": 62,
      "points": 625,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 33,
      "wins": 19,
      "losses": 6,
      "bestRank": 54,
      "status": "Universe"
    },
    {
      "id": "sam-querrey",
      "name": "Sam Querrey",
      "country": "USA",
      "rank": 63,
      "points": 610,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 38,
      "wins": 17,
      "losses": 11,
      "bestRank": 31,
      "status": "Universe"
    },
    {
      "id": "bernard-tomic",
      "name": "Bernard Tomic",
      "country": "Australia",
      "rank": 64,
      "points": 595,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 33,
      "wins": 16,
      "losses": 14,
      "bestRank": 5,
      "status": "Universe"
    },
    {
      "id": "learner-tien",
      "name": "Learner Tien",
      "country": "USA",
      "rank": 65,
      "points": 560,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 20,
      "wins": 18,
      "losses": 10,
      "bestRank": 15,
      "status": "Universe"
    },
    {
      "id": "alex-michelsen",
      "name": "Alex Michelsen",
      "country": "USA",
      "rank": 66,
      "points": 545,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 21,
      "wins": 17,
      "losses": 12,
      "bestRank": 23,
      "status": "Universe"
    },
    {
      "id": "dino-prizmic",
      "name": "Dino Prizmic",
      "country": "Croatia",
      "rank": 67,
      "points": 530,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 20,
      "wins": 11,
      "losses": 10,
      "bestRank": 46,
      "status": "Universe"
    },
    {
      "id": "martin-landaluce",
      "name": "Martin Landaluce",
      "country": "Spain",
      "rank": 68,
      "points": 515,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 20,
      "wins": 14,
      "losses": 14,
      "bestRank": 67,
      "status": "Universe"
    },
    {
      "id": "christopher-eubanks",
      "name": "Christopher Eubanks",
      "country": "USA",
      "rank": 69,
      "points": 500,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "wins": 11,
      "losses": 5,
      "bestRank": 41,
      "status": "Universe"
    },
    {
      "id": "alexander-blockx",
      "name": "Alexander Blockx",
      "country": "Belgium",
      "rank": 70,
      "points": 485,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 21,
      "wins": 13,
      "losses": 5,
      "bestRank": 17,
      "status": "Universe"
    },
    {
      "id": "kyle-edmund",
      "name": "Kyle Edmund",
      "country": "Great Britain",
      "rank": 71,
      "points": 470,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 31,
      "wins": 10,
      "losses": 11,
      "bestRank": 51,
      "status": "Universe"
    },
    {
      "id": "daniel-evans",
      "name": "Daniel Evans",
      "country": "Great Britain",
      "rank": 72,
      "points": 455,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 36,
      "wins": 15,
      "losses": 16,
      "bestRank": 54,
      "status": "Universe"
    },
    {
      "id": "aleksandar-vukic",
      "name": "Aleksandar Vukic",
      "country": "Australia",
      "rank": 73,
      "points": 440,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 30,
      "wins": 14,
      "losses": 12,
      "bestRank": 55,
      "status": "Universe"
    },
    {
      "id": "federico-coria",
      "name": "Federico Coria",
      "country": "Argentina",
      "rank": 74,
      "points": 425,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 34,
      "wins": 15,
      "losses": 6,
      "bestRank": 7,
      "status": "Universe"
    },
    {
      "id": "nuno-borges",
      "name": "Nuno Borges",
      "country": "Portugal",
      "rank": 75,
      "points": 410,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 29,
      "wins": 12,
      "losses": 4,
      "bestRank": 69,
      "status": "Universe"
    },
    {
      "id": "thiago-seyboth-wild",
      "name": "Thiago Seyboth Wild",
      "country": "Brazil",
      "rank": 76,
      "points": 395,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 26,
      "wins": 10,
      "losses": 8,
      "bestRank": 19,
      "status": "Universe"
    },
    {
      "id": "diego-schwartzman",
      "name": "Diego Schwartzman",
      "country": "Argentina",
      "rank": 77,
      "points": 380,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 33,
      "wins": 14,
      "losses": 14,
      "bestRank": 45,
      "status": "Universe"
    },
    {
      "id": "matthew-ebden",
      "name": "Matthew Ebden",
      "country": "Australia",
      "rank": 78,
      "points": 365,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 38,
      "wins": 9,
      "losses": 10,
      "bestRank": 8,
      "status": "Universe"
    },
    {
      "id": "dominik-koepfer",
      "name": "Dominik Koepfer",
      "country": "Germany",
      "rank": 79,
      "points": 350,
      "titles": 0,
      "hand": "Left",
      "surface": "Clay",
      "age": 32,
      "wins": 14,
      "losses": 16,
      "bestRank": 28,
      "status": "Universe"
    },
    {
      "id": "mariano-navone",
      "name": "Mariano Navone",
      "country": "Argentina",
      "rank": 80,
      "points": 335,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 25,
      "wins": 6,
      "losses": 6,
      "bestRank": 40,
      "status": "Universe"
    },
    {
      "id": "tomas-martin-etcheverry",
      "name": "Tomas Martin Etcheverry",
      "country": "Argentina",
      "rank": 81,
      "points": 320,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 26,
      "wins": 13,
      "losses": 14,
      "bestRank": 57,
      "status": "Universe"
    },
    {
      "id": "camilo-ugo-carabelli",
      "name": "Camilo Ugo Carabelli",
      "country": "Argentina",
      "rank": 82,
      "points": 305,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 27,
      "wins": 11,
      "losses": 12,
      "bestRank": 17,
      "status": "Universe"
    },
    {
      "id": "jason-kubler",
      "name": "Jason Kubler",
      "country": "Australia",
      "rank": 83,
      "points": 290,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 33,
      "wins": 8,
      "losses": 15,
      "bestRank": 64,
      "status": "Universe"
    },
    {
      "id": "mackenzie-mcdonald",
      "name": "Mackenzie McDonald",
      "country": "USA",
      "rank": 84,
      "points": 275,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 31,
      "wins": 9,
      "losses": 5,
      "bestRank": 59,
      "status": "Universe"
    },
    {
      "id": "max-purcell",
      "name": "Max Purcell",
      "country": "Australia",
      "rank": 85,
      "points": 260,
      "titles": 0,
      "hand": "Right",
      "surface": "Grass",
      "age": 28,
      "wins": 7,
      "losses": 5,
      "bestRank": 55,
      "status": "Universe"
    },
    {
      "id": "yoshihito-nishioka",
      "name": "Yoshihito Nishioka",
      "country": "Japan",
      "rank": 86,
      "points": 245,
      "titles": 0,
      "hand": "Left",
      "surface": "Hard",
      "age": 30,
      "wins": 5,
      "losses": 3,
      "bestRank": 81,
      "status": "Universe"
    },
    {
      "id": "j-j-wolf",
      "name": "J.J. Wolf",
      "country": "USA",
      "rank": 87,
      "points": 230,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 27,
      "wins": 9,
      "losses": 14,
      "bestRank": 64,
      "status": "Universe"
    },
    {
      "id": "luca-van-assche",
      "name": "Luca Van Assche",
      "country": "France",
      "rank": 88,
      "points": 215,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 22,
      "wins": 8,
      "losses": 5,
      "bestRank": 72,
      "status": "Universe"
    },
    {
      "id": "christopher-o-connell",
      "name": "Christopher O'Connell",
      "country": "Australia",
      "rank": 89,
      "points": 200,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 32,
      "wins": 8,
      "losses": 9,
      "bestRank": 72,
      "status": "Universe"
    },
    {
      "id": "rinky-hijikata",
      "name": "Rinky Hijikata",
      "country": "Australia",
      "rank": 90,
      "points": 185,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 25,
      "wins": 10,
      "losses": 11,
      "bestRank": 45,
      "status": "Universe"
    },
    {
      "id": "taro-daniel",
      "name": "Taro Daniel",
      "country": "Japan",
      "rank": 91,
      "points": 170,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 33,
      "wins": 5,
      "losses": 8,
      "bestRank": 80,
      "status": "Universe"
    },
    {
      "id": "arthur-rinderknech",
      "name": "Arthur Rinderknech",
      "country": "France",
      "rank": 92,
      "points": 155,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 31,
      "wins": 5,
      "losses": 13,
      "bestRank": 68,
      "status": "Universe"
    },
    {
      "id": "yibing-wu",
      "name": "Yibing Wu",
      "country": "China",
      "rank": 93,
      "points": 140,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 26,
      "wins": 5,
      "losses": 6,
      "bestRank": 80,
      "status": "Universe"
    },
    {
      "id": "michael-mmoh",
      "name": "Michael Mmoh",
      "country": "USA",
      "rank": 94,
      "points": 125,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 28,
      "wins": 5,
      "losses": 10,
      "bestRank": 70,
      "status": "Universe"
    },
    {
      "id": "zizou-bergs",
      "name": "Zizou Bergs",
      "country": "Belgium",
      "rank": 95,
      "points": 110,
      "titles": 0,
      "hand": "Right",
      "surface": "Hard",
      "age": 27,
      "wins": 5,
      "losses": 7,
      "bestRank": 34,
      "status": "Universe"
    },
    {
      "id": "benoit-paire",
      "name": "Benoit Paire",
      "country": "France",
      "rank": 96,
      "points": 95,
      "titles": 0,
      "hand": "Right",
      "surface": "Clay",
      "age": 37,
      "wins": 5,
      "losses": 15,
      "bestRank": 40,
      "status": "Universe"
    }
  ],
  "tournaments": [
    {
      "id": "australian-open",
      "name": "Australian Open",
      "category": "Grand Slam",
      "surface": "Hard",
      "champion": "Novak Djokovic",
      "runnerUp": "Carlos Alcaraz",
      "score": "6-7(6), 7-5, 6-4, 3-6, 6-3",
      "mvp": "Rafael Nadal",
      "status": "Completed",
      "story": "Djokovic became the first ATP Universe Grand Slam champion after surviving Alcaraz in five sets. Nadal’s upset over Sinner was the match that changed the tournament."
    },
    {
      "id": "indian-wells",
      "name": "Indian Wells",
      "category": "Masters 1000",
      "surface": "Hard",
      "champion": "Novak Djokovic",
      "runnerUp": "Carlos Alcaraz",
      "score": "6-4, 4-6, 7-6(5)",
      "mvp": "Novak Djokovic",
      "status": "Completed",
      "story": "Djokovic confirmed his early-season dominance by defeating Alcaraz again in a tight hard-court final."
    },
    {
      "id": "miami",
      "name": "Miami",
      "category": "Masters 1000",
      "surface": "Hard",
      "champion": "Carlos Alcaraz",
      "runnerUp": "Novak Djokovic",
      "score": "4-6, 7-5, 6-3",
      "mvp": "Carlos Alcaraz",
      "status": "Completed",
      "story": "Alcaraz answered Djokovic with a comeback title in Miami."
    },
    {
      "id": "monte-carlo",
      "name": "Monte-Carlo",
      "category": "Masters 1000",
      "surface": "Clay",
      "champion": "Rafael Nadal",
      "runnerUp": "Carlos Alcaraz",
      "score": "6-4, 3-6, 6-3",
      "mvp": "Rafael Nadal",
      "status": "Completed",
      "story": "Nadal returned to clay and instantly looked like the king of the surface again."
    },
    {
      "id": "madrid",
      "name": "Madrid",
      "category": "Masters 1000",
      "surface": "Clay",
      "champion": "Novak Djokovic",
      "runnerUp": "Rafael Nadal",
      "score": "4-6, 7-5, 6-4",
      "mvp": "Novak Djokovic",
      "status": "Completed",
      "story": "Djokovic survived Nadal in Madrid to win another huge ATP Universe trophy."
    },
    {
      "id": "rome",
      "name": "Rome",
      "category": "Masters 1000",
      "surface": "Clay",
      "champion": "Rafael Nadal",
      "runnerUp": "Novak Djokovic",
      "score": "6-3, 4-6, 6-4",
      "mvp": "Rafael Nadal",
      "status": "Completed",
      "story": "Nadal’s Rome title made him the emotional favorite for Roland Garros."
    },
    {
      "id": "roland-garros",
      "name": "Roland Garros",
      "category": "Grand Slam",
      "surface": "Clay",
      "champion": "",
      "runnerUp": "",
      "score": "",
      "mvp": "",
      "status": "Next",
      "story": "The clay season arrives in Paris with Sinner still No.1, Djokovic leading the season, and Nadal reborn on clay."
    }
  ],
  "aoMatches": [
    {
      "round": "R16",
      "winner": "Rafael Nadal",
      "loser": "Jannik Sinner",
      "score": "7-6(5), 6-4, 7-5",
      "story": "The biggest shock of the tournament."
    },
    {
      "round": "QF",
      "winner": "Rafael Nadal",
      "loser": "Thanasi Kokkinakis",
      "score": "6-4, 4-6, 7-5, 6-3",
      "story": "Nadal survived the Australian crowd."
    },
    {
      "round": "QF",
      "winner": "Novak Djokovic",
      "loser": "Matteo Berrettini",
      "score": "6-7(5), 6-3, 6-4, 7-6(6)",
      "story": "Djokovic turned the match around with cold precision."
    },
    {
      "round": "QF",
      "winner": "Alex de Minaur",
      "loser": "Alexander Zverev",
      "score": "6-4, 3-6, 7-6(4), 6-4",
      "story": "De Minaur shocked Zverev and gave Australia a semifinalist."
    },
    {
      "round": "QF",
      "winner": "Carlos Alcaraz",
      "loser": "Ben Shelton",
      "score": "7-6(5), 4-6, 6-3, 7-5",
      "story": "Alcaraz handled Shelton’s power under pressure."
    },
    {
      "round": "SF",
      "winner": "Novak Djokovic",
      "loser": "Rafael Nadal",
      "score": "4-6, 7-6(5), 6-3, 7-5",
      "story": "A classic rivalry night."
    },
    {
      "round": "SF",
      "winner": "Carlos Alcaraz",
      "loser": "Alex de Minaur",
      "score": "6-3, 4-6, 6-4, 6-2",
      "story": "Alcaraz ended the Australian dream."
    },
    {
      "round": "Final",
      "winner": "Novak Djokovic",
      "loser": "Carlos Alcaraz",
      "score": "6-7(6), 7-5, 6-4, 3-6, 6-3",
      "story": "Djokovic claimed the first Grand Slam of ATP Universe 2026."
    }
  ],
  "updated": "2026-06-29T23:08:19.123862Z"
};