const $=id=>document.getElementById(id);
let state=JSON.parse(localStorage.getItem("atpV61")||"null")||DATA;
function save(){localStorage.setItem("atpV61",JSON.stringify(state))}
function show(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active");scrollTo(0,0)}
function sorted(){return [...state.players].sort((a,b)=>b.points-a.points).map((p,i)=>({...p,rank:i+1}))}
function renderHome(){let p=sorted()[0];let next=state.tournaments.find(t=>t.status==="Next");$("home").innerHTML=`<div class="hero"><h2>${next.name} is next</h2><p>Permanent ATP Universe database. <b class="gold">${state.players.length}</b> players are saved.</p></div><div class="grid"><div class="card"><b>World No.1</b><div class="value">${p.flag} ${p.name}</div><p>${p.points} pts</p></div><div class="card"><b>Season Leader</b><div class="value">Novak Djokovic</div><p>AO · Indian Wells · Madrid</p></div><div class="card"><b>Clay King</b><div class="value">Rafael Nadal</div><p>Monte-Carlo · Rome</p></div></div><h2>News</h2><div class="grid">${state.news.map(n=>`<div class="card"><h3>${n.title}</h3><p class="muted">${n.body}</p></div>`).join("")}</div>`}
function renderRankings(){ $("rankings").innerHTML=`<h2>Rankings</h2><input id="rankSearch" placeholder="Search..." onkeyup="renderRankTable()"><table id="rankTable"></table>`;renderRankTable()}
function renderRankTable(){let q=($("rankSearch")?.value||"").toLowerCase();let rows=sorted().filter(p=>p.name.toLowerCase().includes(q));$("rankTable").innerHTML=`<tr><th>#</th><th>Player</th><th>Country</th><th>Points</th><th>Titles</th></tr>`+rows.map(p=>`<tr onclick="profile('${p.id}')"><td><b>${p.rank}</b></td><td>${p.flag} ${p.name}</td><td>${p.country}</td><td>${p.points}</td><td>${p.titles}</td></tr>`).join("")}
function renderRace(){let rows=sorted().sort((a,b)=>b.titles-a.titles||b.points-a.points).slice(0,32);$("race").innerHTML=`<h2>ATP Race</h2><table><tr><th>#</th><th>Player</th><th>Titles</th><th>Points</th></tr>${rows.map((p,i)=>`<tr><td>${i+1}</td><td>${p.flag} ${p.name}</td><td>${p.titles}</td><td>${p.points}</td></tr>`).join("")}</table>`}
function renderPlayers(){ $("players").innerHTML=`<h2>Players</h2><input id="playerSearch" placeholder="Search player..." onkeyup="renderPlayerCards()"><div id="playerCards" class="grid"></div>`;renderPlayerCards()}
function renderPlayerCards(){let q=($("playerSearch")?.value||"").toLowerCase();$("playerCards").innerHTML=sorted().filter(p=>p.name.toLowerCase().includes(q)).map(p=>`<div class="player" onclick="profile('${p.id}')"><h3>#${p.rank} ${p.flag} ${p.name}</h3><p>${p.country}</p><span class="chip">${p.points} pts</span><span class="chip">${p.titles} titles</span><span class="chip">${p.wins}-${p.losses}</span><p class="muted">${p.surface} · ${p.hand} · Age ${p.age}</p></div>`).join("")}
function profile(id){let p=state.players.find(x=>x.id===id);$("modal").style.display="block";$("modalBox").innerHTML=`<button onclick="$('modal').style.display='none'">Close</button><div style="display:flex;gap:12px;align-items:center"><div class="avatar">${p.flag}</div><div><h2>${p.name}</h2><p>${p.country}</p></div></div><div class="grid"><div class="card"><b>Rank</b><div class="value">#${p.rank}</div></div><div class="card"><b>Points</b><div class="value">${p.points}</div></div><div class="card"><b>Titles</b><div class="value">${p.titles}</div></div><div class="card"><b>Record</b><div class="value">${p.wins}-${p.losses}</div></div></div><p><span class="chip">${p.hand}</span><span class="chip">${p.surface}</span><span class="chip">Best #${p.bestRank}</span></p>`}
$("modal").onclick=e=>{if(e.target.id==="modal")$("modal").style.display="none"}
function renderTournaments(){ $("tournaments").innerHTML=`<h2>Tournament Center</h2><div class="grid">${state.tournaments.map(t=>`<div class="card"><h3>${t.name} <span class="badge">${t.category}</span></h3><p>${t.surface} · ${t.status}</p><p>Champion: <b class="gold">${t.champion||"TBD"}</b></p><p>Runner-up: ${t.runner||"TBD"}</p><p>${t.score}</p></div>`).join("")}</div>`}
function renderMatches(){ $("matches").innerHTML=`<h2>Match History</h2>${state.matches.map(m=>`<div class="match"><b>${m.round}</b><h3>${m.winner} def. ${m.loser}</h3><p class="gold">${m.score}</p></div>`).join("")}`}
function renderAdmin(){let opts=sorted().map(p=>`<option value="${p.id}">${p.name}</option>`).join("");$("admin").innerHTML=`<h2>Admin Panel</h2><div class="panel"><h3>Add points</h3><select id="adminPlayer">${opts}</select><input id="adminPoints" type="number" placeholder="Points"><button onclick="addPoints()">Save</button><button onclick="resetData()">Reset</button></div>`}
function addPoints(){let p=state.players.find(x=>x.id===$("adminPlayer").value);p.points+=parseInt($("adminPoints").value||0);p.wins++;save();renderAll();alert("Updated "+p.name)}
function resetData(){localStorage.removeItem("atpV61");location.reload()}
function renderAll(){renderHome();renderRankings();renderRace();renderPlayers();renderTournaments();renderMatches();renderAdmin()}
document.addEventListener("DOMContentLoaded",renderAll);